/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ActionForm: typeof import('./src/components/forms/ActionForm.vue')['default']
    ColorPicker: typeof import('./src/components/fields/ColorPicker.vue')['default']
    DatePicker: typeof import('./src/components/fields/DatePicker.vue')['default']
    FormLoader: typeof import('./src/components/FormLoader.vue')['default']
    InputForm: typeof import('./src/components/forms/InputForm.vue')['default']
    EasyButton: typeof import('./src/components/fields/EasyButton.vue')['default']
    EasyCheckboxGroup: typeof import('./src/components/fields/EasyCheckboxGroup.vue')['default']
    EasyIcon: typeof import('./src/components/fields/EasyIcon.vue')['default']
    EasyInput: typeof import('./src/components/fields/EasyInput.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TextFieldTest: typeof import('./src/components/TextFieldTest.vue')['default']
    TimePicker: typeof import('./src/components/fields/TimePicker.vue')['default']
    VAlert: typeof import('vuetify/lib')['VAlert']
    VBtn: typeof import('vuetify/lib')['VBtn']
    VCard: typeof import('vuetify/lib')['VCard']
    VCardText: typeof import('vuetify/lib')['VCardText']
    VCardTitle: typeof import('vuetify/lib')['VCardTitle']
    VCheckbox: typeof import('vuetify/lib')['VCheckbox']
    VCol: typeof import('vuetify/lib')['VCol']
    VColorPicker: typeof import('vuetify/lib')['VColorPicker']
    VCounter: typeof import('vuetify/lib')['VCounter']
    VDatePicker: typeof import('vuetify/lib')['VDatePicker']
    VForm: typeof import('vuetify/lib')['VForm']
    VIcon: typeof import('vuetify/lib')['VIcon']
    VMenu: typeof import('vuetify/lib')['VMenu']
    VProgressCircular: typeof import('vuetify/lib')['VProgressCircular']
    VRadio: typeof import('vuetify/lib')['VRadio']
    VRow: typeof import('vuetify/lib')['VRow']
    VSpacer: typeof import('vuetify/lib')['VSpacer']
    VSwitch: typeof import('vuetify/lib')['VSwitch']
    VTextField: typeof import('vuetify/lib')['VTextField']
    VTimePicker: typeof import('vuetify/lib')['VTimePicker']
    VTooltip: typeof import('vuetify/lib')['VTooltip']
  }
}
